name: devfest

on:
  push: # calls action on push
    branches: [ main ] # calls action on master branch
  pull_request: # calls action on pull request
    branches: [ main ] # calls action on master branch

env:
  flutter_version: "3.0.5"
  java_version: "12.x"

jobs:
  build:
    defaults:
      run:
        working-directory: .

    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“š Git Checkout
      - uses: actions/checkout@v1

      - name: Setup Java
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ env.java_version }}
      
      - name: ğŸ¦ Setup Flutter
      - name: Cache Flutter dependencies
        uses: actions/cache@v1
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.OS }}-flutter-install-cache-${{ env.flutter_version }}
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ env.flutter_version }}
      
      - name: Install dependencies
        run: flutter pub get
      
      - name: Format code
       run: flutter format --dry-run . --set-exit-if-changed
      
      - name: Lint analysis
        run: flutter analyze --no-pub
      
      - name: Build
        run: flutter build apk